<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Обработка-и-анализ-данных-в-Numpy-массивах" data-toc-modified-id="Обработка-и-анализ-данных-в-Numpy-массивах-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Обработка и анализ данных в Numpy-массивах</a></span></li></ul></div>




# Обработка и анализ данных в Numpy-массивах

<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 1</p>

Дано: списки `a,b=[1,1,1],[3,3,3]`

Создать одномерные массивы A и B из списков а и b.

Вычислить выражение $-((B-А)*(B/2))$

In [1]:
import numpy as np

In [1]:
#1 Ваш код здесь
import numpy as np
a, b = [1, 1, 1], [3, 3, 3]
A = np.array(a)
B = np.array(b)
result = -((B - A) * (B / 2))
print(result)

[-3. -3. -3.]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 2</p>

Используя как можно меньше операций в исходном массиве "шахматная доска" np.zeros((8,8)), добиться расстановки кодов "шахматных фигур".

Ожидаемый результат:
```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
 ```

In [1]:
#2. Ваш код здесь
import numpy as np

chess_board = np.zeros((8, 8))

chess_board[0, :] = [-4, -3, -2, -6, -5, -2, -3, -4]

chess_board[7, :] = [4, 3, 2, 6, 5, 2, 3, 4]

chess_board[1, :] = -1
chess_board[6, :] = 1

print(chess_board)



[[-4. -3. -2. -6. -5. -2. -3. -4.]
 [-1. -1. -1. -1. -1. -1. -1. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.]
 [ 4.  3.  2.  6.  5.  2.  3.  4.]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 3</p>

Средствами NumPy рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа

In [2]:
# 3. Ваш код здесь
import numpy as np

even_numbers = np.arange(2, 21, 2)
next_odd_numbers = even_numbers + 1
products = even_numbers * next_odd_numbers

print("Четные числа:", even_numbers)
print("Ближайшие большие нечетные числа:", next_odd_numbers)
print("Произведения:", products)



Четные числа: [ 2  4  6  8 10 12 14 16 18 20]
Ближайшие большие нечетные числа: [ 3  5  7  9 11 13 15 17 19 21]
Произведения: [  6  20  42  72 110 156 210 272 342 420]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 4</p>

Сгенерировать двумерный массив *arr* размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0. Значения округлить (с помощью `np.round()`) до четырех десятичных знаков.

In [3]:
# 4. Ваш код здесь

import numpy as np

arr = np.random.uniform(0, 20, size=(4,7))
arr_norm = (arr - arr.min()) / (arr.max()-arr.min())
arr_round = np.round(arr_norm, 4)
print(arr_round)

[[1.     0.3125 0.3857 0.4243 0.2017 0.5689 0.9128]
 [0.5181 0.7041 0.8107 0.2001 0.2864 0.8666 0.6989]
 [0.     0.1298 0.2805 0.7672 0.6555 0.5136 0.6495]
 [0.116  0.4704 0.2727 0.6648 0.5245 0.0744 0.4819]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 5</p>

5. Имеется массив my_array
```
my_array = np.array([[1,2,3,4,5],
                [6,7,8,9,10],
                [11,12,13,14,15],
                [16,17,18,19,20],
                [21,22,23,24,25]])
```
Напишите код, с помощью которого можно извлечь из него центральный фрагмент размером 3 х 3, с числами 7, 8, 9, 12, 13, 14, 17, 18, 19.

In [4]:
# 5. Ваш код здесь

my_array = np.array([[1,2,3,4,5],
             [6,7,8,9,10],
             [11,12,13,14,15],
             [16,17,18,19,20],
             [21,22,23,24,25]])


central = my_array [2 - 1:2+3, 2-1:2+3]
print(central)


[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 6</p>

Создайте массив *my_sin*, состоящий из синусов элементов массива *my_array*.
Посчитайте, чему равна сумма элементов полученного массива. Ответ округлите до
трёх цифр после запятой.

In [12]:
# 6. Ваш код здесь

import numpy as np 
my_array = np.arange(25).reshape(5, 5)
my_sin = np.sin(my_array)

sum_sin = my_sin.sum()
print("Сумма элементов массива: ", round(sum_sin, 3))

Сумма элементов массива:  0.074


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 7</p>

Создать матрицу из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в матрице. Определить индекс этого значения.

In [20]:
# 7. Ваш код здесь
import numpy as np
matrix = np.random.randint(0, 101, size = (4, 5))

print("Матрица :")
print(matrix)

fl_matrix = matrix.flatten()
flatted_matrix_sorted = np.unique(np.sort(fl_matrix))

if len(flatted_matrix_sorted) >= 2:
    second_hightest_value = flatted_matrix_sorted[-2]
    indices = np.where(matrix == second_hightest_value)

print("\nВторое сверху значение в матрице: ", second_hightest_value)
print("Индексы этого значения: ")

for i in range(len(indices[0])):
        print(f"({indices[0][i]}, {indices[1][i]})")
else:
    print("\nВ матрице недостаточно уникальных значений.")

Матрица :
[[98 54 34 69 78]
 [37 20 46 96 83]
 [63 35 96 66 81]
 [38 19 33 65 60]]

Второе сверху значение в матрице:  96
Индексы этого значения: 
(1, 3)
(2, 2)

В матрице недостаточно уникальных значений.


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 8</p>

Задать два двухмерных массива *ar1* и *ar2* размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двухмерный массив размерности (4, 7), каждый элемент которого представляет собой максимум (минимум, среднее) из двух значений, находящихся на аналогичной позиции в массивах *ar1*, *ar2*.

In [24]:
# 8. Ваш код здесь

import numpy as np 
arr1 = np.random.randint(0, 11, size = (4, 7))
arr2 = np.random.randint(0, 11, size = (4, 7))

print("arr1:")
print(arr1)
print("arr2:")
print(arr2)

maximum_array = np.maximum(arr1, arr2)
print("\nМассив, максимум из 2х значений")
print(maximum_array)

minimum_array = np.minimum(arr1, arr2)
print("\nМассив, минимум из 2х значений")
print(minimum_array)

average_array = (arr1 + arr2) / 2 
print("\nМассив, среднее из 2х значений")
print(average_array)

arr1:
[[ 7 10  5  7  1  8 10]
 [ 2  1  6  2  8  1  0]
 [ 0  9  9  8  2  8  8]
 [ 0  6  9  4  1  0  8]]
arr2:
[[ 7 10  5  2 10  3  7]
 [ 3  4  5  3  2  0  0]
 [ 3  9  6  8  4  8  4]
 [ 1 10  3  3  3  8  3]]

Массив, максимум из 2х значений
[[ 7 10  5  7 10  8 10]
 [ 3  4  6  3  8  1  0]
 [ 3  9  9  8  4  8  8]
 [ 1 10  9  4  3  8  8]]

Массив, минимум из 2х значений
[[ 7 10  5  2  1  3  7]
 [ 2  1  5  2  2  0  0]
 [ 0  9  6  8  2  8  4]
 [ 0  6  3  3  1  0  3]]

Массив, среднее из 2х значений
[[ 7.  10.   5.   4.5  5.5  5.5  8.5]
 [ 2.5  2.5  5.5  2.5  5.   0.5  0. ]
 [ 1.5  9.   7.5  8.   3.   8.   6. ]
 [ 0.5  8.   6.   3.5  2.   4.   5.5]]


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 9</p>

Имеется массив *great_array*
```
first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T
```
Чему равна сумма элементов массива great_array, значение которых больше 50?

In [25]:
#9 Ваш код здесь
import numpy as np

first = [x**(1/2) for x in range(100)]
second = [x**(1/3) for x in range(100, 200)]
third = [x/y for x in range(200,300,2) for y in [3,5]]
great_array = np.array([first, second, third]).T


sum_50 = np.sum(great_array[great_array > 50])

print("Сумма элементов массива, значение которых > 50", sum_50)

Сумма элементов массива, значение которых > 50 5470.0


<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 10</p>

Переведите массив *great_array* в одномерную форму. Какое значение в получившемся массиве имеет элемент с индексом 150?

In [29]:
# 10. Ваш код здесь



<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 11</p>

Получить индексы, для которых элементы массивов A и B совпадают.
```
A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])
```
Ожидается результат:

```
array([1, 3, 5, 7])
```

In [12]:
# 11.

A = np.array([1,2,3,2,3,4,3,4,5,6])
B = np.array([7,2,10,2,7,4,9,4,9,8])

# Ваш код здесь



<p style="font-size:125%; color:#119988; background-color:#EEE">Задание 12</p>

Создайте три массива: массив четных чисел от 2 до 20, массив ближайших к числам первого массива бОльших нечётных чисел, массив векторного произведения первого массива на второй. Соедините все массивы в один двумерный массив, расположив исходные массивы в столбцах.

In [3]:
# 12.  Ваш код здесь

